pipeline {

    agent any

    parameters {
        string(name: 'GIT_REPO_URL', defaultValue: 'https://github.com/ItsJor/sw_r_assist.git', description: 'Repository link for build - java')
        string(name: 'GIT_BUILD_BRANCH', defaultValue: 'main', description: 'Branch for the build')
        choice(name: 'BUILD_ENVIRONMENT', choices: ['dev', 'uat', 'prod'], description: 'Environment to build out')
    }

    environment {
        SPRING_BOOT_ACTIVE = params.BUILD_ENVIRONMENT
    }

    stages {

        stage('Clone repository') {
            steps {
                echo 'Cloning repository from: ' + params.GIT_REPO_URL
                echo 'Cloning on branch: ' + params.GIT_BUILD_BRANCH
                git(url: params.GIT_REPO_URL, branch: params.GIT_BUILD_BRANCH, credentialsId: 'github_pat')
            }
        }
        stage('Build project') {
            steps {
                sh './mvnw clean install'
            }
        }
        stage('Pause to see workspace') {
            steps {
                input(message: 'Pause')
            }
        }
        
    }

    post {
        always {
            echo 'Cleaning workspace'
            cleanWs()
        }
    }

}